### ISSUE TITLE
[meta] Breaking changes before v2-beta release

### ISSUE THREAD

**Issue by amrbashir** [tauri-apps/tauri#7756]
#### Public API changes:

- [X] Remove custom protocol types and replace with `http` crate types - https://github.com/tauri-apps/tauri/pull/7754
- [x] Remove `tauri::api` module, not sure if it is needed, it still has hidden exports but ultimately it should be removed and replace with a public API if needed - https://github.com/tauri-apps/tauri/pull/7874
- [x] `path` and `plugin` modules both, have a `Result` type alias, where they should be using `tauri::Result` instead and not have Error types on their own - https://github.com/tauri-apps/tauri/pull/7875
- [x] ~~Make almost all callbacks (where it makes sense), return a `tauri::Result` because most of our APIs return `tauri::Result` and would be easier to use `?` operator.~~
- [x] Remove `rand` and `uuid` crates, our usages of it could be replaced with an atomically incremented counter - https://github.com/tauri-apps/tauri/pull/7939
- [x] change `Env.args` to pull from `std::env::args_os` instead of `std::env::args` - https://github.com/tauri-apps/tauri/pull/7876
- [x] Consistent naming
  - [x] Scope struct names, we have `FsScope`, then we have `ipc::Scope` - https://github.com/tauri-apps/tauri/pull/7944
  - [x] `TrayIconBuilder/TrayIcon::on_tray_event` should be renamed to `TrayIconBuilder/TrayIcon::on_tray_icon_event` - https://github.com/tauri-apps/tauri/pull/7943
  - [x] [Environment variables](https://github.com/tauri-apps/tauri/blob/29818de682146a75cd9a886f7b215154cad1d42d/tooling/cli/ENVIRONMENT_VARIABLES.md) used by tauri and tauri-cli is inconsistent and needs major renaming with possibly prefixing each var with `TAURI_<SCOPE>_<VAR>` - https://github.com/tauri-apps/tauri/pull/7949
  A few examples but not limited to: 
   	- `TAURI_FIPS_COMPLIANT` should be `TAURI_BUNDLER_WIX_FIPS_COMPLIANT`
   	- `TAURI_PRIVATE_KEY` relies on `TAURI_KEY_PASSWORD` and so it should be renamed to `TAURI_PRIVATE_KEY_PASSWORD`
   	- `APPLE_ID` and `APPLE_PASSWORD` should probably be prefixed with `TAURI_` unless these env vars are somewhat of a convention used by other tools, in that case, it should be fine to keep as is.
  - [x] ~~`Event` and `RunEvent`, I think `RunEvent` should be renamed to `Event` and `Event` should be changed to `EmittedEvent` and a variant under `Event` (which was previously named `RunEvent`)~~
   	
#### Internal changes:
- [x] primitives in `@tauri-apps/api`, like `invoke`, `Channel`, `convertFileSrc` and probably all exports from [`@tauri-apps/api/tauri` module](https://github.com/tauri-apps/tauri/blob/29818de682146a75cd9a886f7b215154cad1d42d/tooling/api/src/tauri.ts), should be all just a shim for the globally defined equivalents in [`scripts/core.js`](https://github.com/tauri-apps/tauri/blob/29818de682146a75cd9a886f7b215154cad1d42d/core/tauri/scripts/core.js) - https://github.com/tauri-apps/tauri/pull/7942
- [x] ~~Move from TS to JS with JSDoc for @tauri-apps/api npm package, see [discord wg-forum post](https://discord.com/channels/616186924390023171/1146797909170466846)~~
- [x] #8036

This list is open for discussion, I just made it because I keep forgetting about them and feel free to add more as you see fit.

cc @tauri-apps/wg-tauri

**Comment by lucasfernog** [comment]
I like most of this, but I'm not sure about `Make almost all callbacks (where it makes sense), return a tauri::Result because most of our APIs return tauri::Result and would be easier to use ? operator.`. This one makes it harder to use custom Result types.

**Comment by lorenzolewis** [comment]
I'm not sure if these qualify under "breaking changes", but I'm tracking these in https://github.com/tauri-apps/tauri-docs/issues/1344 :

- [ ] https://github.com/tauri-apps/tauri/issues/7696
- [x] https://github.com/tauri-apps/tauri/pull/7744
- [x] https://github.com/tauri-apps/tauri/issues/7749 - https://github.com/tauri-apps/tauri/pull/7990
- [x] (optional, more messages and info that can be post 2.0) https://github.com/tauri-apps/tauri/issues/7572 - https://github.com/tauri-apps/tauri/pull/7952

**Comment by FabianLars** [comment]
I'd like to request another one, merging the 2 updater configs into one. It may be a bit awkward to have the cli/bundler care about plugin configs but that's still wayyyyy less awkward than having 2 updater configs imo.
Also we'll likely need something similar for the shell and deep link plugins anyway (to bundle the additional binaries needed for them if the plugins are used)

- [ ] Merge `bundle.updater` into `plugins.updater`

**Comment by amrbashir** [comment]
> I like most of this, but I'm not sure about `Make almost all callbacks (where it makes sense), return a tauri::Result because most of our APIs return tauri::Result and would be easier to use ? operator.`. This one makes it harder to use custom Result types.

My bad, I actually thought we have more than one callback that returns a result, turns out it is only `.setup`, Should be fine to keep as is then.

**Comment by lorenzolewis** [comment]
Met @nathan234 at RustConf, Nathan mentioned looking at integrating ART for the Android side of 2.0. Feel free to join the conversation here, open a new issue/PR, or join us on Discord!

**Comment by amrbashir** [comment]
> * `Event` and `RunEvent`, I think `RunEvent` should be renamed to `Event` and `Event` should be changed to `EmittedEvent` and a variant under `Event` (which was previously named `RunEvent`)

While trying to implement this change, I had a change of heart because the JS side uses `Event` as the type name of the so called `EmittedEvent` in Rust and that doesn't make sense, so I decided to keep the names as they are for now.

if anyone feels like this change is still needed, let me know

**Comment by amrbashir** [comment]
> Move from TS to JS with JSDoc for @tauri-apps/api npm package, see [discord wg-forum post](https://discord.com/channels/616186924390023171/1146797909170466846)

Decided to keep TS and instead opted into simplifying the output JS files in https://github.com/tauri-apps/tauri/pull/8025 which makes:
1. The generated files easier to edit and patch locally
2. `Go to definition` doesn't work as expected but `Go to source definition` does

**Comment by amrbashir** [comment]
Closing this as most items are now implemented, the remaining 2 items could be added later, and will be tracked in their respective issues.
